In [79]:
import numpy as np
from operator import attrgetter
%run Node.ipynb

In [80]:
# implement P.Q using list
# implement customized put() based on algo_type
class CustomizedPriotiryQueue:
    # algo_type: uniform_cost, GBFS, aStar
    def __init__(self, algo_type):
        self.puzzle_list = []
        self.algo_type = algo_type

    def put(self, node):
        #check duplicate
        has_duplicate = False
        
        for idx, obj in enumerate(self.puzzle_list):
            if node.__eq__(obj):
                has_duplicate = True
                # print("has duplicate at index: ", idx)
                
                # compare cost/h/f and replace node
                if self.algo_type == "uniform_cost" and obj.get_g_val() > node.get_g_val():
                    self.puzzle_list[idx] = node
                elif self.algo_type == "GBFS" and obj.get_h_val() > node.get_h_val():
                    self.puzzle_list[idx] = node
                elif self.algo_type == "aStar" and obj.get_f_val() > node.get_f_val():
                    self.puzzle_list[idx] = node
                else:
                    print("Don't need replace")
        
        # if don't have duplicate
        if not has_duplicate:
            self.puzzle_list.append(node)
        
        # sort the current puzzle_list
        # print("===========sort list")
        if self.algo_type == "uniform_cost":
            self.puzzle_list.sort(key = attrgetter('g_val'))
        elif self.algo_type == "GBFS":
            self.puzzle_list.sort(key = attrgetter('h_val'))
        elif self.algo_type == "aStar":
            self.puzzle_list.sort(key = attrgetter('f_val'))
        else:
            print("Wrong algo_type")

    def get(self):
        return self.puzzle_list.pop(0)

    def __repr__(self):
        str = "puzzle_list:\n"
        for obj in enumerate(self.puzzle_list):
            str += obj.__repr__() + "\n"
        return str

In [83]:
# test

# node1 = Node(np.array([[1,2,3,4],[5,6,7,0]]), None, 1, 3)
# node2 = Node(np.array([[5,2,7,4],[1,6,3,0]]), None, 2, 2)
# node3 = Node(np.array([[1,2,3,4],[5,6,7,0]]), None, 3, 1)

# self_set = CustomizedPriotiryQueue("GBFS")
# self_set.put(node1)
# print(self_set)

# self_set.put(node2)
# print(self_set)

# self_set.put(node3)
# print(self_set)

# node = self_set.get()
# print("get: ",node)
# print(self_set)






===========sort list
puzzle_list:
(0, Node(current puzzle=[[1 2 3 4]
 [5 6 7 0]], parent_puzzle=None, h(node)=1, g(node)=3, f(node)=4))

===========sort list
puzzle_list:
(0, Node(current puzzle=[[1 2 3 4]
 [5 6 7 0]], parent_puzzle=None, h(node)=1, g(node)=3, f(node)=4))
(1, Node(current puzzle=[[5 2 7 4]
 [1 6 3 0]], parent_puzzle=None, h(node)=2, g(node)=2, f(node)=4))

has duplicate at index:  0
Don't need replace
===========sort list
puzzle_list:
(0, Node(current puzzle=[[1 2 3 4]
 [5 6 7 0]], parent_puzzle=None, h(node)=1, g(node)=3, f(node)=4))
(1, Node(current puzzle=[[5 2 7 4]
 [1 6 3 0]], parent_puzzle=None, h(node)=2, g(node)=2, f(node)=4))

get:  Node(current puzzle=[[1 2 3 4]
 [5 6 7 0]], parent_puzzle=None, h(node)=1, g(node)=3, f(node)=4)
puzzle_list:
(0, Node(current puzzle=[[5 2 7 4]
 [1 6 3 0]], parent_puzzle=None, h(node)=2, g(node)=2, f(node)=4))

