In [73]:
import numpy as np
from copy import copy, deepcopy
import queue
%run utilityFunc.ipynb
%run Node.ipynb

In [74]:
# read puzzle file
f = open("puzzle.txt", "r")
puzzle_list = [] # contains list of nparray for each puzzle
for line in f:
    # print(line) #test
    puzzle_nparr = np.array(list(line.split(" ")), dtype=int)
    dim1_len = int(len(puzzle_nparr)/4) #calculate length of first dimension
    puzzle_nparr = puzzle_nparr.reshape(dim1_len, 4) #reshape nparray to 2*4 multi-dimentional array
    puzzle_list.append(puzzle_nparr)
# print(puzzle_list)


puzzle_test = np.array([[3,0,1,4],[2, 6, 5, 7], [8, 9, 10, 11], [12,13,14,15]])
puzzle_dim_shape = puzzle_test.shape
sol = np.argwhere(puzzle_test == 15) # get index of specific element
print(sol)

[[3 3]]


In [75]:
# puzzle_test = regular_move(puzzle_dim_shape, sol, puzzle_test, "right")
# puzzle_test = wrapping_move(puzzle_dim_shape, sol, puzzle_test)
# puzzle_test = opposed_diagonally_move(puzzle_dim_shape, sol, puzzle_test)
# puzzle_test = adjacent_diagonally_move(puzzle_dim_shape, sol, puzzle_test)

print(puzzle_test)

[[ 3  0  1  4]
 [ 2  6  5  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [76]:
def get_successor(puzzle_dim_shape, elt_position, puzzle, cost):
    original_puzzle = deepcopy(puzzle)
    successor_prio_queue = queue.PriorityQueue()
    successor = []
    # (successor_node, parent_node, total_cost)
    successor.append((regular_move(puzzle_dim_shape, elt_position, puzzle, "up"), original_puzzle, cost+1))
    successor.append((regular_move(puzzle_dim_shape, elt_position, puzzle, "down"), original_puzzle, cost+1))
    successor.append((regular_move(puzzle_dim_shape, elt_position, puzzle, "left"), original_puzzle, cost+1))
    successor.append((regular_move(puzzle_dim_shape, elt_position, puzzle, "right"), original_puzzle, cost+1))
    successor.append((wrapping_move(puzzle_dim_shape, elt_position, puzzle), original_puzzle, cost+2))
    successor.append((opposed_diagonally_move(puzzle_dim_shape, elt_position, puzzle), original_puzzle, cost+3))
    successor.append((adjacent_diagonally_move(puzzle_dim_shape, elt_position, puzzle), original_puzzle, cost+3))

    successor = [i for i in successor if i[0] is not None] # eliminate None puzzle node
    print(successor) # test

    for tup in successor:
        successor_prio_queue.put((tup[2], Node(tup[0], tup[1], 0)))
    for q_item in successor_prio_queue.queue:
        print(q_item)
    return successor_prio_queue


# return a list including all goal state
def generate_goal(puzzle):
    goal = []
    first_dim, second_dim = puzzle.shape
    puzzle_flatten = puzzle.flatten() # flatten to one dimentinal
    sorted_puzzle = np.sort(puzzle_flatten) # sort array
    sorted_puzzle = np.append(sorted_puzzle[1:], 0)

    goal1 = sorted_puzzle.reshape(first_dim, second_dim)
    goal.append(goal1)
    
    goal2 = np.full((first_dim, second_dim), 0)
    idx = 0
    for s in range(second_dim):
        for f in range(first_dim):
            goal2[f, s] = sorted_puzzle[idx]
            idx += 1
    goal.append(goal2)
    # print(goal)
    return goal


def check_goal(node, goal):
    return np.array_equal(node, goal[0]) or np.array_equal(node, goal[1])

get_successor(puzzle_dim_shape, sol, puzzle_test, 0)
# goal = generate_goal(puzzle_test)
# puzzle_test = deepcopy(goal[1])
# print(check_goal(puzzle_test, goal))



[(array([[ 3,  0,  1,  4],
       [ 2,  6,  5,  7],
       [ 8,  9, 10, 15],
       [12, 13, 14, 11]]), array([[ 3,  0,  1,  4],
       [ 2,  6,  5,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]]), 1), (array([[ 3,  0,  1,  4],
       [ 2,  6,  5,  7],
       [ 8,  9, 10, 11],
       [12, 13, 15, 14]]), array([[ 3,  0,  1,  4],
       [ 2,  6,  5,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]]), 1), (array([[ 3,  0,  1,  4],
       [ 2,  6,  5,  7],
       [ 8,  9, 10, 11],
       [15, 13, 14, 12]]), array([[ 3,  0,  1,  4],
       [ 2,  6,  5,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]]), 2), (array([[15,  0,  1,  4],
       [ 2,  6,  5,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  3]]), array([[ 3,  0,  1,  4],
       [ 2,  6,  5,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]]), 3), (array([[ 3,  0,  1,  4],
       [ 2,  6,  5,  7],
       [ 8,  9, 15, 11],
       [12, 13, 14, 10]]), array([[ 3,  0,  1,  4],
       [ 2,  6,  5,  7],
       [ 8

In [ ]:
#Uniform Cost Algo
puzzle = puzzle_list[0]
def uniform_cost_algo(start_puzzle):
    closed_list = []
    open_queue = queue.PriorityQueue() # elt: (cost_val, Node(node, parent_node, h_val))
    open_queue.put(0, Node(start_puzzle, None, 0))

    while open_queue:
        cost, node = open_queue.get()
        if 

    